### ISSUE TITLE
NPE when instantiating the NeuroML converter

### ISSUE THREAD

**Issue by tarelli** [NeuroML/org.neuroml.model#18]
Some exceptions I am finding in the log. Doesn't happen all the time.

**Comment by tarelli** [comment]
```
org.neuroml.model.util.NeuroMLException: Problem loading NeuroML document 
[2016-02-12 16:02:51.826] ERROR ExperimentRunChecker         System.err                                                        	at org.neuroml.model.util.NeuroMLConverter.loadNeuroML(NeuroMLConverter.java:131) 
[2016-02-12 16:02:51.826] ERROR ExperimentRunChecker         System.err                                                        	at org.geppetto.model.neuroml.utils.OptimizedLEMSReader.readAllFormats(OptimizedLEMSReader.java:79) 
[2016-02-12 16:02:51.826] ERROR ExperimentRunChecker         System.err                                                        	at org.geppetto.model.neuroml.services.LEMSModelInterpreterService.importType(LEMSModelInterpreterService.java:97) 
[2016-02-12 16:02:51.827] ERROR ExperimentRunChecker         System.err                                                        	at org.geppetto.simulation.visitor.ImportTypesVisitor.caseImportType(ImportTypesVisitor.java:91) 
[2016-02-12 16:02:51.827] ERROR ExperimentRunChecker         System.err                                                        	at org.geppetto.model.types.util.TypesSwitch.doSwitch(TypesSwitch.java:94) 
[2016-02-12 16:02:51.827] ERROR ExperimentRunChecker         System.err                                                        	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53) 
[2016-02-12 16:02:51.827] ERROR ExperimentRunChecker         System.err                                                        	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69) 
[2016-02-12 16:02:51.827] ERROR ExperimentRunChecker         System.err                                                        	at org.geppetto.model.util.GeppettoModelTraversal.apply(GeppettoModelTraversal.java:52) 
[2016-02-12 16:02:51.827] ERROR ExperimentRunChecker         System.err                                                        	at org.geppetto.simulation.manager.RuntimeProject.<init>(RuntimeProject.java:127) 
[2016-02-12 16:02:51.827] ERROR ExperimentRunChecker         System.err                                                        	at org.geppetto.simulation.manager.GeppettoManager.loadProject(GeppettoManager.java:138) 
[2016-02-12 16:02:51.827] ERROR ExperimentRunChecker         System.err                                                        	at org.geppetto.simulation.manager.ExperimentRunManager.runExperiment(ExperimentRunManager.java:143) 
[2016-02-12 16:02:51.827] ERROR ExperimentRunChecker         System.err                                                        	at org.geppetto.simulation.manager.ExperimentRunChecker.run(ExperimentRunManager.java:304) 
[2016-02-12 16:02:51.827] ERROR ExperimentRunChecker         System.err                                                        	at java.util.TimerThread.mainLoop(Timer.java:555) 
[2016-02-12 16:02:51.827] ERROR ExperimentRunChecker         System.err                                                        	at java.util.TimerThread.run(Timer.java:505) 
[2016-02-12 16:02:51.828] ERROR ExperimentRunChecker         System.err                                                        Caused by: javax.xml.bind.UnmarshalException 
[2016-02-12 16:02:51.828] ERROR ExperimentRunChecker         System.err                                                         - with linked exception: 
[2016-02-12 16:02:51.828] ERROR ExperimentRunChecker         System.err                                                        [org.xml.sax.SAXException: FWK005 parse may not be called while parsing.] 
[2016-02-12 16:02:51.828] ERROR ExperimentRunChecker         System.err                                                        	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:335) 
[2016-02-12 16:02:51.828] ERROR ExperimentRunChecker         System.err                                                        	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:512) 
[2016-02-12 16:02:51.828] ERROR ExperimentRunChecker         System.err                                                        	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:209) 
[2016-02-12 16:02:51.828] ERROR ExperimentRunChecker         System.err                                                        	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:175) 
[2016-02-12 16:02:51.828] ERROR ExperimentRunChecker         System.err                                                        	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157) 
[2016-02-12 16:02:51.828] ERROR ExperimentRunChecker         System.err                                                        	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:214) 
[2016-02-12 16:02:51.828] ERROR ExperimentRunChecker         System.err                                                        	at org.neuroml.model.util.NeuroMLConverter.loadNeuroML(NeuroMLConverter.java:128) 
[2016-02-12 16:02:51.828] ERROR ExperimentRunChecker         System.err                                                        	... 13 more 
[2016-02-12 16:02:51.828] ERROR ExperimentRunChecker         System.err                                                        Caused by: org.xml.sax.SAXException: FWK005 parse may not be called while parsing. 
[2016-02-12 16:02:51.829] ERROR ExperimentRunChecker         System.err                                                        	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1253) 
[2016-02-12 16:02:51.829] ERROR ExperimentRunChecker         System.err                                                        	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649) 
[2016-02-12 16:02:51.829] ERROR ExperimentRunChecker         System.err                                                        	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:203) 
[2016-02-12 16:02:51.829] ERROR ExperimentRunChecker         System.err                                                        	... 17 more 

```

**Comment by tarelli** [comment]
<img width="743" alt="screen shot 2016-02-12 at 16 13 30" src="https://cloud.githubusercontent.com/assets/81127/13012534/94f95e98-d1a3-11e5-8c27-38a85543d325.png">
<img width="479" alt="screen shot 2016-02-12 at 16 01 17" src="https://cloud.githubusercontent.com/assets/81127/13012533/94f7d7da-d1a3-11e5-8f25-e54d420727a2.png">

**Comment by pgleeson** [comment]
Can you send the NML it's trying to load?

**Comment by tarelli** [comment]
![screen shot 2016-02-13 at 11 59 29](https://cloud.githubusercontent.com/assets/81127/13027472/81222822-d249-11e5-96d8-38d50cfbda39.png)

**Comment by tarelli** [comment]
@pgleeson I will as soon as I can reproduce it again, many times though the exceptions happens just when instantiating the NeuroMLConverter, no arguments passed, see above.

**Comment by tarelli** [comment]
@pgleeson @adrianq https://gist.github.com/tarelli/44d60119864ad5b7d216 there you go, however I noticed this happens after the previous one so maybe there's something already wrong beforehand that has to do with the schema.

**Comment by pgleeson** [comment]
@tarelli not sure if it's a problem with the gist or the file, but it's truncated at the end, no closing elements.

Is it something to do with the file not getting fully downloaded before being parsed?

**Comment by pgleeson** [comment]
Seems like this is no longer a problem for you @tarelli? Reopen if you see it again.
