### ISSUE TITLE
ArrayIndexOutOfBoundsException with some h5 files

### ISSUE THREAD

**Issue by mattearnshaw** [NeuroML/org.neuroml.model#22]
nc_ca1 h5 file gives

```
Error reading request, ignored java.lang.ArrayIndexOutOfBoundsException: 3
        at org.neuroml.model.util.hdf5.NetworkHelper.getLocation(NetworkHelper.java:178)
        at org.geppetto.model.neuroml.modelInterpreterUtils.PopulateTypes.createPopulationTypeVariable(PopulateTypes.java:565)
```

this is fixed in org.neuroml.model development but awaiting release

**Comment by mattearnshaw** [comment]
all seems to be working now
